#!/bin/bash

# Arguments:
# $1: Longitude (x) of the lookup.      ex: -120
# $2: Latitude (y) of the lookup.       ex: 39
# $3: Folder + tif name of the lookup.  ex: gfs/tmp/SurfaceTemp
# $4: Starting date. (YYYYMMDD)         ex: 20180601
# $5: Starting time. (HH) - UTC         ex: 06
# $6: Number of hours.                  ex: 48
# $7: Hours between each forecast.      ex: 1

LONGITUDE=$1
LATITUDE=$2
FILEPREPEND=$3
STARTDATE=$4
STARTTIME=$5
NUMHOURS=$6
STEPSIZE=$7

for i in `seq 0 $STEPSIZE $NUMHOURS`
do
    NEWTIME=`date -d "$STARTDATE $STARTTIME +$i hours" +%Y%m%dT%H`
    NEWTIME+="0000000Z"
    FILE=$FILEPREPEND
    FILE+="_"
    FILE+=$NEWTIME
    FILE+=".tif"
    echo `gdallocationinfo -wgs84 $FILE $LONGITUDE $LATITUDE -valonly --config GDAL_DISABLE_READDIR_ON_OPEN YES --config GDAL_NUM_THREADS ALL_CPUS --config GDAL_FORCE_CACHING YES --config GDAL_CACHEMAX 35% --config GTIFF_VIRTUAL_MEM_IO IF_ENOUGH_RAM `
done